title: 🖼️ Photo Stream
baseline: Your personal photo gallery
description: Cecil Photo Stream is a photo gallery static site
baseurl: https://photo-stream.cecil.app/
image: preview.png
theme:
  - applanding
  - netlify
language: en
languages:
  - code: en
    locale: en
  - code: fr
    locale: fr
    config:
      baseline: Votre galerie photo personnelle
      description: Cecil Photo Stream est un site statique de galerie de photos
applanding:
  buttons:
    - name: Netlify
      url: https://app.netlify.com/start/deploy?repository=https://github.com/Cecilapp/photo-stream&stack=cms
      image: https://www.netlify.com/img/deploy/button.svg
    - name: Vercel
      url: https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2FCecilapp%2Fphoto-stream&project-name=photo-stream&repository-name=photo-stream&demo-title=Photo%20Stream&demo-description=Super%20simple%20self%20hosted%20photo%20stream%2C%20powered%20by%20Cecil.&demo-url=https%3A%2F%2Fphoto-stream-demo.cecil.app&demo-image=https%3A%2F%2Fgithub.com%2FCecilapp%2Fphoto-stream.cecil.app%2Fraw%2Fmain%2Fassets%2Fpreview.png
      image: https://vercel.com/button/default.svg
  source: https://github.com/Cecilapp/photo-stream
  documentation: https://github.com/Cecilapp/photo-stream#readme
  demo: https://photo-stream-demo.cecil.app
  screenshot:
    desktop:
      light: preview.png
    #  dark: preview-dark.png
    #mobile:
    #  light: mobile-preview.png
    #  dark: mobile-preview-dark.png
netlify:
  redirects:
    - from: cecil-photo-stream.netlify.app/*
      to: photo-stream.cecil.app/:splat
      status: 301
      force: true
  redirect_by_language: true
